/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as PortalPortalIndexRouteImport } from './routes/_portal/portal/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardTasksIndexRouteImport } from './routes/_dashboard/tasks/index'
import { Route as DashboardHostsIndexRouteImport } from './routes/_dashboard/hosts/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/_dashboard/events/index'
import { Route as DashboardEgressIpsIndexRouteImport } from './routes/_dashboard/egress-ips/index'
import { Route as DashboardUsersUserIdRouteImport } from './routes/_dashboard/users/$userId'
import { Route as DashboardHostsHostIdRouteImport } from './routes/_dashboard/hosts/$hostId'
import { Route as PortalPortalHostsHostIdRouteImport } from './routes/_portal/portal/hosts/$hostId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalPortalIndexRoute = PortalPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => PortalRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostsIndexRoute = DashboardHostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEgressIpsIndexRoute = DashboardEgressIpsIndexRouteImport.update({
  id: '/egress-ips/',
  path: '/egress-ips/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostsHostIdRoute = DashboardHostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalPortalHostsHostIdRoute = PortalPortalHostsHostIdRouteImport.update({
  id: '/portal/hosts/$hostId',
  path: '/portal/hosts/$hostId',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/hosts/$hostId': typeof DashboardHostsHostIdRoute
  '/users/$userId': typeof DashboardUsersUserIdRoute
  '/egress-ips/': typeof DashboardEgressIpsIndexRoute
  '/events/': typeof DashboardEventsIndexRoute
  '/hosts/': typeof DashboardHostsIndexRoute
  '/tasks/': typeof DashboardTasksIndexRoute
  '/users/': typeof DashboardUsersIndexRoute
  '/portal/': typeof PortalPortalIndexRoute
  '/portal/hosts/$hostId': typeof PortalPortalHostsHostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/hosts/$hostId': typeof DashboardHostsHostIdRoute
  '/users/$userId': typeof DashboardUsersUserIdRoute
  '/egress-ips': typeof DashboardEgressIpsIndexRoute
  '/events': typeof DashboardEventsIndexRoute
  '/hosts': typeof DashboardHostsIndexRoute
  '/tasks': typeof DashboardTasksIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/portal': typeof PortalPortalIndexRoute
  '/portal/hosts/$hostId': typeof PortalPortalHostsHostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/hosts/$hostId': typeof DashboardHostsHostIdRoute
  '/_dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/_dashboard/egress-ips/': typeof DashboardEgressIpsIndexRoute
  '/_dashboard/events/': typeof DashboardEventsIndexRoute
  '/_dashboard/hosts/': typeof DashboardHostsIndexRoute
  '/_dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_portal/portal/': typeof PortalPortalIndexRoute
  '/_portal/portal/hosts/$hostId': typeof PortalPortalHostsHostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/hosts/$hostId'
    | '/users/$userId'
    | '/egress-ips/'
    | '/events/'
    | '/hosts/'
    | '/tasks/'
    | '/users/'
    | '/portal/'
    | '/portal/hosts/$hostId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/hosts/$hostId'
    | '/users/$userId'
    | '/egress-ips'
    | '/events'
    | '/hosts'
    | '/tasks'
    | '/users'
    | '/portal'
    | '/portal/hosts/$hostId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_portal'
    | '/login'
    | '/_dashboard/'
    | '/_dashboard/hosts/$hostId'
    | '/_dashboard/users/$userId'
    | '/_dashboard/egress-ips/'
    | '/_dashboard/events/'
    | '/_dashboard/hosts/'
    | '/_dashboard/tasks/'
    | '/_dashboard/users/'
    | '/_portal/portal/'
    | '/_portal/portal/hosts/$hostId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_portal/portal/': {
      id: '/_portal/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalPortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tasks/': {
      id: '/_dashboard/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/hosts/': {
      id: '/_dashboard/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof DashboardHostsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/events/': {
      id: '/_dashboard/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/egress-ips/': {
      id: '/_dashboard/egress-ips/'
      path: '/egress-ips'
      fullPath: '/egress-ips/'
      preLoaderRoute: typeof DashboardEgressIpsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/$userId': {
      id: '/_dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/hosts/$hostId': {
      id: '/_dashboard/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof DashboardHostsHostIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_portal/portal/hosts/$hostId': {
      id: '/_portal/portal/hosts/$hostId'
      path: '/portal/hosts/$hostId'
      fullPath: '/portal/hosts/$hostId'
      preLoaderRoute: typeof PortalPortalHostsHostIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardHostsHostIdRoute: typeof DashboardHostsHostIdRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardEgressIpsIndexRoute: typeof DashboardEgressIpsIndexRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardHostsIndexRoute: typeof DashboardHostsIndexRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardHostsHostIdRoute: DashboardHostsHostIdRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardEgressIpsIndexRoute: DashboardEgressIpsIndexRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardHostsIndexRoute: DashboardHostsIndexRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PortalRouteChildren {
  PortalPortalIndexRoute: typeof PortalPortalIndexRoute
  PortalPortalHostsHostIdRoute: typeof PortalPortalHostsHostIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPortalIndexRoute: PortalPortalIndexRoute,
  PortalPortalHostsHostIdRoute: PortalPortalHostsHostIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
