package http

import (
	"context"
	"crypto/rand"
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"math/big"
	nethttp "net/http"
	"strings"
	"time"

	"database/sql"
	"golang.org/x/crypto/bcrypt"

	"github.com/zanel1u/cloud-cli-proxy/internal/controlplane/credgen"
	"github.com/zanel1u/cloud-cli-proxy/internal/store/repository"
)

type AdminUserStore interface {
	ListUsers(context.Context) ([]repository.User, error)
	GetUser(context.Context, string) (repository.User, error)
	CreateUser(context.Context, repository.CreateUserParams) (repository.User, error)
	UpdateUserStatus(context.Context, string, string) (repository.User, error)
	DeleteUser(context.Context, string) error
	UpdateUserPassword(context.Context, string, string) error
	UpdateUserEntryPassword(context.Context, string, string) error
	UpdateUserSSHKeys(ctx context.Context, userID, publicKey, privateKey, keyType string) error
	CreateSSHKey(ctx context.Context, userID, purpose, label, publicKey, privateKey, keyType, fingerprint string) (repository.SSHKey, error)
	DeleteAutoGeneratedInboundSSHKeys(ctx context.Context, userID string) error
	ListHostsByUserID(context.Context, string) ([]repository.Host, error)
	UpdateUserExpiry(context.Context, string, *time.Time) (repository.User, error)
}

type AdminUsersHandler struct {
	logger *slog.Logger
	store  AdminUserStore
	events EventRecorder
}

func NewAdminUsersHandler(logger *slog.Logger, store AdminUserStore, events EventRecorder) *AdminUsersHandler {
	return &AdminUsersHandler{logger: logger, store: store, events: events}
}

func (h *AdminUsersHandler) List() nethttp.Handler {
	return nethttp.HandlerFunc(func(w nethttp.ResponseWriter, r *nethttp.Request) {
		users, err := h.store.ListUsers(r.Context())
		if err != nil {
			h.logger.Error("list users failed", "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "list users failed"})
			return
		}
		for i := range users {
			users[i].PasswordHash = ""
			users[i].EntryPassword = ""
		}
		writeJSON(w, nethttp.StatusOK, map[string]any{"users": users})
	})
}

func (h *AdminUsersHandler) Get() nethttp.Handler {
	return nethttp.HandlerFunc(func(w nethttp.ResponseWriter, r *nethttp.Request) {
		userID := r.PathValue("userID")

		user, err := h.store.GetUser(r.Context(), userID)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				writeJSON(w, nethttp.StatusNotFound, map[string]string{"error": "user not found"})
				return
			}
			h.logger.Error("get user failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "get user failed"})
			return
		}

		hosts, err := h.store.ListHostsByUserID(r.Context(), userID)
		if err != nil {
			h.logger.Error("list hosts by user failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "list hosts failed"})
			return
		}

		user.PasswordHash = ""
		user.EntryPassword = ""
		writeJSON(w, nethttp.StatusOK, map[string]any{"user": user, "hosts": hosts})
	})
}

type createUserRequest struct {
	Username string `json:"username"`
}

func (h *AdminUsersHandler) Create() nethttp.Handler {
	return nethttp.HandlerFunc(func(w nethttp.ResponseWriter, r *nethttp.Request) {
		var req createUserRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "invalid request body"})
			return
		}

		req.Username = strings.TrimSpace(req.Username)
		if len(req.Username) < 3 || len(req.Username) > 50 {
			writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "username must be 3-50 characters"})
			return
		}

		plainPassword := credgen.GenerateLoginPassword()
		hash, err := bcrypt.GenerateFromPassword([]byte(plainPassword), bcrypt.DefaultCost)
		if err != nil {
			h.logger.Error("hash password failed", "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "internal error"})
			return
		}

		entryPassword := credgen.GenerateEntryPassword()
		sshPublicKey, sshPrivateKey, keyErr := credgen.GenerateSSHKeyPair("ed25519", req.Username)
		if keyErr != nil {
			h.logger.Error("generate ssh key pair failed", "error", keyErr)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "generate ssh key failed"})
			return
		}
		fingerprint := credgen.ComputeFingerprint(sshPublicKey)
		if fingerprint == "" {
			h.logger.Error("compute ssh fingerprint failed (empty)")
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "compute ssh fingerprint failed"})
			return
		}

		shortID := credgen.GenerateShortID()

		const maxRetries = 5
		var user repository.User
		for attempt := 0; attempt < maxRetries; attempt++ {
			user, err = h.store.CreateUser(r.Context(), repository.CreateUserParams{
				Username:      req.Username,
				PasswordHash:  string(hash),
				ShortID:       shortID,
				EntryPassword: entryPassword,
			})
			if err == nil {
				break
			}
			if strings.Contains(err.Error(), "short_id") && (strings.Contains(err.Error(), "unique") || strings.Contains(err.Error(), "duplicate")) {
				shortID = credgen.GenerateShortID()
				continue
			}
			break
		}
		if err != nil {
			if strings.Contains(err.Error(), "unique") || strings.Contains(err.Error(), "duplicate") {
				writeJSON(w, nethttp.StatusConflict, map[string]string{"error": "username already exists"})
				return
			}
			h.logger.Error("create user failed", "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "create user failed"})
			return
		}

		if err := h.store.UpdateUserSSHKeys(r.Context(), user.ID, sshPublicKey, sshPrivateKey, "ed25519"); err != nil {
			h.logger.Error("persist user ssh keys failed", "user_id", user.ID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "persist ssh keys failed"})
			return
		}
		if _, err := h.store.CreateSSHKey(r.Context(), user.ID, "inbound", "auto-generated", sshPublicKey, sshPrivateKey, "ed25519", fingerprint); err != nil {
			h.logger.Error("create ssh_keys row failed", "user_id", user.ID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "create ssh key row failed"})
			return
		}

		if h.events != nil {
			if _, err := h.events.RecordEvent(r.Context(), repository.RecordEventParams{
				UserID:   &user.ID,
				Level:    "info",
				Type:     "admin.user.created",
				Message:  "管理员创建用户",
				Metadata: map[string]any{"operator": "admin", "username": user.Username},
			}); err != nil {
				h.logger.Error("record event failed", "type", "admin.user.created", "error", err)
			}
		}

		user.PasswordHash = ""
		user.EntryPassword = ""
		user.SSHPublicKey = ""
		user.SSHPrivateKey = ""
		writeJSON(w, nethttp.StatusCreated, map[string]any{
			"user":                user,
			"short_id":            user.ShortID,
			"password":            plainPassword,
			"entry_password":      entryPassword,
			"ssh_public_key":      sshPublicKey,
			"ssh_private_key":     sshPrivateKey,
			"ssh_key_fingerprint": fingerprint,
		})
	})
}

// RegenerateCredentials 为指定用户重新生成 entry_password + ed25519 SSH 密钥对，
// 覆盖 users 表凭据列与 ssh_keys 表中 label='auto-generated' 的旧入站行。
// 凭据明文仅在响应中返回一次，调用方需自行妥善保存。
func (h *AdminUsersHandler) RegenerateCredentials() nethttp.Handler {
	return nethttp.HandlerFunc(func(w nethttp.ResponseWriter, r *nethttp.Request) {
		userID := r.PathValue("userID")

		user, err := h.store.GetUser(r.Context(), userID)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				writeJSON(w, nethttp.StatusNotFound, map[string]string{"error": "user not found"})
				return
			}
			h.logger.Error("get user for credentials regenerate failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "get user failed"})
			return
		}

		entryPassword := credgen.GenerateEntryPassword()
		sshPublicKey, sshPrivateKey, keyErr := credgen.GenerateSSHKeyPair("ed25519", user.Username)
		if keyErr != nil {
			h.logger.Error("generate ssh key pair failed", "user_id", userID, "error", keyErr)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "generate ssh key failed"})
			return
		}
		fingerprint := credgen.ComputeFingerprint(sshPublicKey)
		if fingerprint == "" {
			h.logger.Error("compute ssh fingerprint failed (empty)", "user_id", userID)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "compute ssh fingerprint failed"})
			return
		}

		if err := h.store.UpdateUserEntryPassword(r.Context(), userID, entryPassword); err != nil {
			h.logger.Error("update user entry password failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "update entry password failed"})
			return
		}
		if err := h.store.UpdateUserSSHKeys(r.Context(), userID, sshPublicKey, sshPrivateKey, "ed25519"); err != nil {
			h.logger.Error("update user ssh keys failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "update ssh keys failed"})
			return
		}
		if err := h.store.DeleteAutoGeneratedInboundSSHKeys(r.Context(), userID); err != nil {
			h.logger.Error("delete old auto-generated ssh keys failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "delete old ssh keys failed"})
			return
		}
		if _, err := h.store.CreateSSHKey(r.Context(), userID, "inbound", "auto-generated", sshPublicKey, sshPrivateKey, "ed25519", fingerprint); err != nil {
			h.logger.Error("create new ssh_keys row failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "create ssh key row failed"})
			return
		}

		if h.events != nil {
			if _, err := h.events.RecordEvent(r.Context(), repository.RecordEventParams{
				UserID:   &userID,
				Level:    "info",
				Type:     "admin.user.credentials_regenerated",
				Message:  "管理员重新生成用户 SSH 凭据",
				Metadata: map[string]any{"operator": "admin", "username": user.Username},
			}); err != nil {
				h.logger.Error("record event failed", "type", "admin.user.credentials_regenerated", "error", err)
			}
		}

		writeJSON(w, nethttp.StatusOK, map[string]any{
			"entry_password":      entryPassword,
			"ssh_public_key":      sshPublicKey,
			"ssh_private_key":     sshPrivateKey,
			"ssh_key_fingerprint": fingerprint,
		})
	})
}

type updateStatusRequest struct {
	Status string `json:"status"`
}

func (h *AdminUsersHandler) UpdateStatus() nethttp.Handler {
	return nethttp.HandlerFunc(func(w nethttp.ResponseWriter, r *nethttp.Request) {
		userID := r.PathValue("userID")

		var req updateStatusRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "invalid request body"})
			return
		}

		if req.Status != "active" && req.Status != "disabled" {
			writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "status must be active or disabled"})
			return
		}

		user, err := h.store.UpdateUserStatus(r.Context(), userID, req.Status)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				writeJSON(w, nethttp.StatusNotFound, map[string]string{"error": "user not found"})
				return
			}
			h.logger.Error("update user status failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "update status failed"})
			return
		}

		if h.events != nil {
			if _, err := h.events.RecordEvent(r.Context(), repository.RecordEventParams{
				UserID:   &user.ID,
				Level:    "info",
				Type:     "admin.user.updated",
				Message:  "管理员修改用户状态",
				Metadata: map[string]any{"operator": "admin", "new_status": req.Status},
			}); err != nil {
				h.logger.Error("record event failed", "type", "admin.user.updated", "error", err)
			}
		}

		writeJSON(w, nethttp.StatusOK, map[string]any{"user": user})
	})
}

type updateExpiryRequest struct {
	ExpiresAt *string `json:"expires_at"`
}

func (h *AdminUsersHandler) UpdateExpiry() nethttp.Handler {
	return nethttp.HandlerFunc(func(w nethttp.ResponseWriter, r *nethttp.Request) {
		userID := r.PathValue("userID")

		var req updateExpiryRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "invalid request body"})
			return
		}

		var expiresAt *time.Time
		if req.ExpiresAt != nil {
			t, err := time.Parse(time.RFC3339, *req.ExpiresAt)
			if err != nil {
				writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "expires_at must be RFC3339 format"})
				return
			}
			if t.Before(time.Now()) {
				writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "expires_at must be in the future"})
				return
			}
			expiresAt = &t
		}

		user, err := h.store.UpdateUserExpiry(r.Context(), userID, expiresAt)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				writeJSON(w, nethttp.StatusNotFound, map[string]string{"error": "user not found"})
				return
			}
			h.logger.Error("update user expiry failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "update expiry failed"})
			return
		}

		if h.events != nil {
			var expiryVal any
			if expiresAt != nil {
				expiryVal = expiresAt.Format(time.RFC3339)
			}
			if _, err := h.events.RecordEvent(r.Context(), repository.RecordEventParams{
				UserID:   &user.ID,
				Level:    "info",
				Type:     "admin.user.updated",
				Message:  "管理员修改用户到期时间",
				Metadata: map[string]any{"operator": "admin", "expires_at": expiryVal},
			}); err != nil {
				h.logger.Error("record event failed", "type", "admin.user.updated", "error", err)
			}
		}

		writeJSON(w, nethttp.StatusOK, map[string]any{"user": user})
	})
}

func (h *AdminUsersHandler) Delete() nethttp.Handler {
	return nethttp.HandlerFunc(func(w nethttp.ResponseWriter, r *nethttp.Request) {
		userID := r.PathValue("userID")

		if err := h.store.DeleteUser(r.Context(), userID); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				writeJSON(w, nethttp.StatusNotFound, map[string]string{"error": "user not found"})
				return
			}
			h.logger.Error("delete user failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "delete user failed"})
			return
		}

		if h.events != nil {
			if _, err := h.events.RecordEvent(r.Context(), repository.RecordEventParams{
				UserID:   &userID,
				Level:    "info",
				Type:     "admin.user.deleted",
				Message:  "管理员删除用户",
				Metadata: map[string]any{"operator": "admin"},
			}); err != nil {
				h.logger.Error("record event failed", "type", "admin.user.deleted", "error", err)
			}
		}

		w.WriteHeader(nethttp.StatusNoContent)
	})
}

type rotatePasswordRequest struct {
	NewPassword *string `json:"new_password"`
}

func (h *AdminUsersHandler) RotatePassword() nethttp.Handler {
	return nethttp.HandlerFunc(func(w nethttp.ResponseWriter, r *nethttp.Request) {
		userID := r.PathValue("userID")

		var req rotatePasswordRequest
		body, err := io.ReadAll(io.LimitReader(r.Body, 1<<20))
		if err != nil {
			writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "read body failed"})
			return
		}
		if len(strings.TrimSpace(string(body))) > 0 {
			if err := json.Unmarshal(body, &req); err != nil {
				writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "invalid request body"})
				return
			}
		}

		var newPassword string
		if req.NewPassword != nil {
			newPassword = strings.TrimSpace(*req.NewPassword)
		}
		if newPassword == "" {
			const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%&*"
			b := make([]byte, 20)
			for i := range b {
				n, err := rand.Int(rand.Reader, big.NewInt(int64(len(charset))))
				if err != nil {
					h.logger.Error("generate random password failed", "error", err)
					writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "internal error"})
					return
				}
				b[i] = charset[n.Int64()]
			}
			newPassword = string(b)
		} else {
			if len(newPassword) < 8 || len(newPassword) > 128 {
				writeJSON(w, nethttp.StatusBadRequest, map[string]string{"error": "login password must be 8-128 characters"})
				return
			}
		}

		hash, err := bcrypt.GenerateFromPassword([]byte(newPassword), bcrypt.DefaultCost)
		if err != nil {
			h.logger.Error("hash password failed", "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "internal error"})
			return
		}

		if err := h.store.UpdateUserPassword(r.Context(), userID, string(hash)); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				writeJSON(w, nethttp.StatusNotFound, map[string]string{"error": "user not found"})
				return
			}
			h.logger.Error("rotate password failed", "user_id", userID, "error", err)
			writeJSON(w, nethttp.StatusInternalServerError, map[string]string{"error": "rotate password failed"})
			return
		}

		if h.events != nil {
			if _, err := h.events.RecordEvent(r.Context(), repository.RecordEventParams{
				UserID:   &userID,
				Level:    "info",
				Type:     "admin.user.password_rotated",
				Message:  "管理员轮换用户密码",
				Metadata: map[string]any{"operator": "admin"},
			}); err != nil {
				h.logger.Error("record event failed", "type", "admin.user.password_rotated", "error", err)
			}
		}

		writeJSON(w, nethttp.StatusOK, map[string]any{"new_password": newPassword})
	})
}

