-- Host SSH identity: each host gets its own short_id + entry_password
-- This moves SSH authentication from user-centric to host-centric.
-- SSH login: ssh <host_short_id>@proxy -p 2222 with host's entry_password

ALTER TABLE hosts ADD COLUMN IF NOT EXISTS short_id TEXT UNIQUE;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS entry_password TEXT NOT NULL DEFAULT '';

-- Migrate existing data: copy entry_password from user to their primary host
UPDATE hosts
SET entry_password = (
    SELECT u.entry_password FROM users u
    WHERE u.id = hosts.user_id
      AND u.entry_password != ''
      AND hosts.entry_password = ''
)
WHERE EXISTS (
    SELECT 1 FROM users u
    WHERE u.id = hosts.user_id
      AND u.entry_password != ''
      AND hosts.entry_password = ''
);

-- Note: In SQLite, we cannot use PL/pgSQL to generate random short_ids.
-- short_id will be generated by the application layer when hosts are created.
-- Existing hosts without short_id will have NULL, which the app layer handles.
